// src/db/seeds/01_products.ts

import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
    await knex("products").del();
    await knex('products').insert([
        {
            id: 1,
            name: 'The Classic Longboard',
            description: `Rediscover the soul of surfing with The Classic Longboard. This board is all about effortless paddling, early wave entry, and unmatched stability...`,
            price_in_pence: 69999,
            image_url: '/surfboard.webp',
            category: 'surfboard',
            brand: 'WaveRider',
            rating: 4.5,
            deal_type: null,
            deal_discount: null,
            model: 'Classic-90',
            dimensions: `9'0" x 22.5" x 3"`,
            volume: '72L',
            ability: 'Beginner to Advanced',
            conditions: 'Knee to shoulder-high waves',
            construction: 'EPS Foam Core / Epoxy Shell',
            fin_system: 'Single Fin Box',
        },
        {
            id: 2,
            name: 'High-Performance Shortboard',
            description: `Unleash your full potential in critical waves with the ShredStix Pro-X...`,
            price_in_pence: 74999,
            image_url: '/surfboard.webp',
            category: 'surfboard',
            brand: 'ShredStix',
            rating: 4.8,
            deal_type: 'percentage',
            deal_discount: 10,
            model: 'Pro-X',
            dimensions: `6'2" x 19" x 2.5"`,
            volume: '30.5L',
            ability: 'Intermediate to Pro',
            conditions: 'Chest-high to double-overhead',
            construction: 'PU Foam / Carbon Tail Patch',
            fin_system: 'FCS II Thruster',
        },
        {
            id: 3,
            name: 'Pro Comp Leash',
            description: `When you're charging a heavy set, the last thing you need to worry about is your gear...`,
            price_in_pence: 2999,
            image_url: '/surfboard.webp',
            category: 'accessory',
            brand: 'StayTied',
            rating: 4.7,
            deal_type: null,
            deal_discount: null,
            model: 'Comp-6',
            dimensions: null,
            volume: null,
            ability: null,
            conditions: null,
            construction: null,
            fin_system: null,
        },
        {
            id: 4,
            name: 'Eco-Friendly Surf Wax',
            description: `Get superior grip that's good for your board and great for the ocean...`,
            price_in_pence: 499,
            image_url: '/surfboard.webp',
            category: 'accessory',
            brand: 'StickyLeaf',
            rating: 4.9,
            deal_type: null,
            deal_discount: null,
            model: 'CoolWater',
            dimensions: null,
            volume: null,
            ability: null,
            conditions: null,
            construction: null,
            fin_system: null,
        },
        {
            id: 5,
            name: 'Retro Rocket Fish',
            description: `Turn average, mushy days into your personal playground...`,
            price_in_pence: 54995,
            image_url: '/surfboard.webp',
            category: 'surfboard',
            brand: 'WaveRider',
            rating: 4.6,
            deal_type: null,
            deal_discount: null,
            model: 'Rocket-58',
            dimensions: `8'0" x 22" x 3.2"`,
            volume: '85L',
            ability: 'First-time Beginner',
            conditions: 'Small, rolling waves',
            construction: 'Soft IXPE Deck / HDPE Slick Bottom',
            fin_system: 'Flexible Tri-Fin (Included)',
        },
        {
            id: 6,
            name: 'The Dolphin Soft Top',
            description: `The perfect start to a lifelong surfing adventure...`,
            price_in_pence: 29950,
            image_url: '/surfboard.webp',
            category: 'surfboard',
            brand: 'AquaGlide',
            rating: 4.2,
            deal_type: 'fixed_amount',
            deal_discount: 2500,
            model: 'Dolphin-80',
            dimensions: `5'8" x 21" x 2.6"`,
            volume: '34L',
            ability: 'All Levels',
            conditions: 'Ankle to head-high waves',
            construction: 'PU Foam / Gloss Finish',
            fin_system: 'Futures Twin Fin',
        },
        {
            id: 7,
            name: '3/2mm Furnace Comp Wetsuit',
            description: `Extend your summer sessions and stay warm without sacrificing performance...`,
            price_in_pence: 24999,
            image_url: '/surfboard.webp',
            category: 'accessory',
            brand: 'ThermoSurf',
            rating: 4.7,
            deal_type: null,
            deal_discount: null,
            model: 'Furnace-Comp',
            dimensions: null,
            volume: null,
            ability: null,
            conditions: null,
            construction: null,
            fin_system: null,
        },
        {
            id: 8,
            name: 'Carbon-Tech Thruster Fins',
            description: `Upgrade your ride and feel the difference...`,
            price_in_pence: 8995,
            image_url: '/surfboard.webp',
            category: 'accessory',
            brand: 'ShredStix',
            rating: 4.9,
            deal_type: null,
            deal_discount: null,
            model: 'Carbon-Thruster',
            dimensions: null,
            volume: null,
            ability: null,
            conditions: null,
            construction: null,
            fin_system: null,
        },
        {
            id: 9,
            name: '5-Piece Arch Tail Pad',
            description: `Lock in your back foot for critical maneuvers with the GripTide Arch-5 tail pad...`,
            price_in_pence: 3499,
            image_url: '/surfboard.webp',
            category: 'accessory',
            brand: 'GripTide',
            rating: 4.4,
            deal_type: null,
            deal_discount: null,
            model: 'Arch-5',
            dimensions: null,
            volume: null,
            ability: null,
            conditions: null,
            construction: null,
            fin_system: null,
        },
        {
            id: 10,
            name: 'Daylight Thruster Board Bag',
            description: `Your board is an investment—protect it. The BoardShield Daylight bag is essential for everyday use...`,
            price_in_pence: 7495,
            image_url: '/surfboard.webp',
            category: 'accessory',
            brand: 'BoardShield',
            rating: 4.6,
            deal_type: 'percentage',
            deal_discount: 15,
            model: 'Daylight-62',
            dimensions: null,
            volume: null,
            ability: null,
            conditions: null,
            construction: null,
            fin_system: null,
        },
        {
            id: 11,
            name: 'Helium TJ Hull Rider Longboard',
            description: `A modern classic designed by Taylor Jensen, this board combines a traditional hull design for smooth, effortless glide with Firewire's advanced Helium technology. The result is an incredibly light, durable, and responsive longboard that excels in a wide range of conditions, from small peelers to overhead points. Its 2+1 fin setup allows for versatility, whether you prefer a classic single-fin feel or more drive with side bites.`,
            price_in_pence: 122500,
            image_url: '/surfboard.webp',
            category: 'surfboard',
            brand: 'Firewire',
            rating: 4.8,
            deal_type: null,
            deal_discount: null,
            model: 'TJ Hull Rider',
            dimensions: `9'0" x 22 1/2" x 2 3/4"`,
            volume: '69.4L',
            ability: 'Intermediate to Advanced',
            conditions: 'Ankle to head-high waves',
            construction: 'Helium Technology (EPS/Epoxy)',
            fin_system: 'Futures 2+1',
        },
        {
            id: 12,
            name: 'Ladies Advantage 3/2mm Chest Zip Wetsuit',
            description: `Stay warm without sacrificing flexibility in the Hurley Advantage 3/2mm wetsuit. Engineered with Exoflex Light neoprene, this suit offers excellent stretch for unrestricted movement. The chest zip entry system is watertight and easy to get on and off. A plush hollow-fiber lining in the chest and back panels wicks water and insulates for maximum warmth, making it the perfect choice for shoulder-season surfs.`,
            price_in_pence: 29995,
            image_url: '/surfboard.webp',
            category: 'accessory',
            brand: 'Hurley',
            rating: 4.7,
            deal_type: null,
            deal_discount: null,
            model: 'Advantage 3/2mm CZ',
            dimensions: null,
            volume: null,
            ability: null,
            conditions: null,
            construction: null,
            fin_system: null,
        },
        {
            id: 13,
            name: 'The Hugger Roller Bag 60L',
            description: `The perfect travel companion for any surf adventure. The Hugger 60L combines the portability of a backpack with the convenience of a roller bag. Its robust, lightweight construction protects your gear, while the large main compartment opens fully for easy access. Featuring Db's signature Rib Cage Construction™ and sturdy wheels, this bag is built to withstand the rigors of travel. Hook it up to other Db bags for seamless transport through the airport.`,
            price_in_pence: 22900,
            image_url: '/surfboard.webp',
            category: 'accessory',
            brand: 'Db',
            rating: 4.9,
            deal_type: 'percentage',
            deal_discount: 5,
            model: 'Hugger Roller 60L',
            dimensions: null,
            volume: null,
            ability: null,
            conditions: null,
            construction: null,
            fin_system: null,
        },
    ]);
};
